
[functions.brainactive-get-content]
enabled = true
verify_jwt = false
import_map = "./functions/brainactive-get-content/deno.json"
entrypoint = "./functions/brainactive-get-content/index.ts"

[functions.brainactive-get-questions]
enabled = true
verify_jwt = false
entrypoint = "./functions/brainactive-get-questions/index.ts"

[functions.brainactive-submit-attempt]
enabled = true
verify_jwt = false
entrypoint = "./functions/brainactive-submit-attempt/index.ts"

[functions.brainactive-get-progress]
enabled = true
verify_jwt = false
entrypoint = "./functions/brainactive-get-progress/index.ts"

[functions.brainactive-apply-referral]
enabled = true
verify_jwt = false
entrypoint = "./functions/brainactive-apply-referral/index.ts"

[functions.brainactive-report-question]
enabled = true
verify_jwt = false
entrypoint = "./functions/brainactive-report-question/index.ts"
